# Standard library
import unittest

# Third-party
from _typeshed import Incomplete

class TestMyFunctions(unittest.TestCase):
    run_path: str
    settings: Incomplete
    tune_trial: str
    data_train: Incomplete
    data_valid: Incomplete
    sha: str
    hostname_tsa: str
    hostname_nid: str
    input_data: Incomplete
    target_data: Incomplete
    generator: Incomplete
    center: int
    scale: float
    def setUp(self) -> None: ...
    def test_load_data(self) -> None: ...
    def test_train_and_evaluate_model(
        self,
        mock_load_pretrained_model,
        mock_train_without_ray_tune,
        mock_train_with_ray_tune,
    ) -> None: ...
    def test_train_with_ray_tune(self) -> None: ...
    def test_get_runtime_env(self) -> None: ...
    def test_get_scheduler(self) -> None: ...
    def test_get_tune_config(self) -> None: ...
    def test_get_callbacks(self) -> None: ...
    def test_rsync_mlruns(self, mock_run) -> None: ...
    def test_train_without_ray_tune(self, mock_train_model_simple) -> None: ...
    def test_define_filters(self) -> None: ...
    def test_cbr(self) -> None: ...
    def test_down(self) -> None: ...
    def test_up(self) -> None: ...
    def test_compile_generator(self) -> None: ...
    def test_write_png(self) -> None: ...
    def test_train_step(self) -> None: ...
    def test_setup_directories(self) -> None: ...
    def test_create_optimizer(self) -> None: ...
    def test_validate_epoch(self): ...
