name: alditest
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiohttp-cors=0.7.0
  - aiorwlock=1.3.0
  - aiosignal=1.3.1
  - alabaster=0.7.13
  - alembic=1.9.4
  - alsa-lib=1.2.8
  - anaconda-client=1.11.0
  - anyio=3.6.2
  - appdirs=1.4.4
  - arrow-cpp=9.0.0
  - asciitree=0.3.3
  - astroid=2.14.2
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=22.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.2
  - binutils_impl_linux-64=2.40
  - black=23.1.0
  - blessed=1.19.1
  - blinker=1.5
  - boa=0.14.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - cairo=1.16.0
  - cartopy=0.21.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgrib=0.9.10.3
  - cfgv=3.3.1
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - clyent=1.2.2
  - codespell=2.2.2
  - colorama=0.4.6
  - colorful=0.5.4
  - conda=23.1.0
  - conda-build=3.23.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - configparser=5.3.0
  - contourpy=1.0.7
  - cryptography=39.0.0
  - cuda=11.7.1
  - cuda-cccl=11.7.91
  - cuda-command-line-tools=11.7.1
  - cuda-compiler=11.7.1
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.7.99
  - cuda-cuobjdump=11.7.91
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.7.91
  - cuda-demo-suite=12.0.140
  - cuda-documentation=12.0.140
  - cuda-driver-dev=11.7.99
  - cuda-gdb=12.0.140
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.7.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.0.140
  - cuda-nsight-compute=12.0.1
  - cuda-nvcc=11.7.99
  - cuda-nvdisasm=12.0.140
  - cuda-nvml-dev=11.7.91
  - cuda-nvprof=12.0.146
  - cuda-nvprune=11.7.91
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.0.146
  - cuda-runtime=11.7.1
  - cuda-sanitizer-api=12.0.140
  - cuda-toolkit=11.7.1
  - cuda-tools=11.7.1
  - cuda-visual-tools=11.7.1
  - cudatoolkit=11.7.0
  - cudatoolkit-dev=11.4.0
  - cudnn=8.4.1.50
  - curl=7.87.0
  - cycler=0.11.0
  - databricks-cli=0.17.4
  - dataclasses=0.8
  - dbus=1.13.6
  - decorator=5.1.1
  - dill=0.3.6
  - distlib=0.3.6
  - docker-py=6.0.0
  - docrep=0.3.2
  - docutils=0.18.1
  - eccodes=2.28.0
  - entrypoints=0.4
  - exceptiongroup=1.1.0
  - executing=1.2.0
  - expat=2.5.0
  - fastapi=0.92.0
  - fasteners=0.17.3
  - fftw=3.3.10
  - filelock=3.9.0
  - findlibs=0.0.2
  - flake8=6.0.0
  - flake8-black=0.3.5
  - flask=2.2.3
  - flatbuffers=2.0.8
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freeglut=3.2.2
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - funcargparse=0.2.5
  - gast=0.4.0
  - gcc_impl_linux-64=12.2.0
  - gdk-pixbuf=2.42.10
  - gds-tools=1.5.1.14
  - geos=3.11.1
  - gettext=0.21.1
  - gflags=2.2.2
  - gfortran_impl_linux-64=12.2.0
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glib=2.74.1
  - glib-tools=2.74.1
  - glob2=0.7
  - glog=0.6.0
  - google-api-core=2.11.0
  - google-auth=2.16.1
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - googleapis-common-protos=1.57.1
  - gpustat=1.0.0
  - graphite2=1.3.13
  - graphviz=7.1.0
  - greenlet=2.0.2
  - grpc-cpp=1.47.1
  - grpcio=1.47.1
  - gsl=2.7
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.33
  - gtk2=2.24.33
  - gts=0.7.6
  - gunicorn=20.1.0
  - gxx_impl_linux-64=12.2.0
  - h11=0.14.0
  - h5py=3.8.0
  - harfbuzz=6.0.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - identify=2.5.18
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=4.13.0
  - importlib_resources=5.12.0
  - iniconfig=2.0.0
  - ipdb=0.13.11
  - ipython=8.10.0
  - isort=5.12.0
  - itsdangerous=2.1.2
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_core=5.2.0
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.9.0
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.66
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=11.10.3.66
  - libcublas-dev=11.10.3.66
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.2.124
  - libcufile=1.5.1.14
  - libcufile-dev=1.5.1.14
  - libcups=2.3.3
  - libcurand=10.3.1.124
  - libcurand-dev=10.3.1.124
  - libcurl=7.87.0
  - libcusolver=11.4.0.1
  - libcusolver-dev=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.4.91
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgd=2.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libglu=9.0.0
  - libgomp=12.2.0
  - libgoogle-cloud=2.3.0
  - libgpg-error=1.46
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - liblief=0.12.3
  - libllvm11=11.1.0
  - libllvm15=15.0.7
  - libmamba=1.1.0
  - libmambapy=1.1.0
  - libnetcdf=4.9.1
  - libnghttp2=1.51.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.7.4.75
  - libnsl=2.0.0
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.8.0.2
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libprotobuf=3.21.12
  - librsvg=2.54.4
  - libsanitizer=12.2.0
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsolv=0.7.22
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=252
  - libthrift=0.16.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunwind=1.6.2
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - livereload=2.6.3
  - llvm-openmp=15.0.7
  - llvmlite=0.39.1
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - mako=1.2.4
  - mamba=1.1.0
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib=3.7.0
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdurl=0.1.0
  - mkl=2022.2.1
  - mlflow=2.1.1
  - mpg123=1.31.2
  - msgpack-python=1.0.4
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy=1.0.1
  - mypy_extensions=1.0.0
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbformat=5.7.3
  - ncurses=6.3
  - nlopt=2.7.1
  - nodeenv=1.7.0
  - nodejs=18.12.1
  - nsight-compute=2022.4.1.6
  - nspr=4.35
  - nss=3.88
  - numba=0.56.4
  - numcodecs=0.11.0
  - numpy=1.23.5
  - nvidia-ml-py=11.495.46
  - oauthlib=3.2.2
  - opencensus=0.11.1
  - opencensus-context=0.1.3
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - orc=1.8.0
  - packaging=22.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pango=1.50.13
  - paramiko=3.0.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - patch=2.7.6
  - patchelf=0.17.2
  - pathlib=1.0.1
  - pathspec=0.11.0
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.0.0
  - pluggy=1.0.0
  - ply=3.11
  - pooch=1.6.0
  - pre-commit=3.0.4
  - proj=9.1.1
  - prometheus_client=0.16.0
  - prometheus_flask_exporter=0.22.2
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - protobuf=4.21.12
  - psutil=5.9.4
  - psyplot=1.4.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - py-spy=0.3.14
  - pyarrow=9.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.5
  - pydocstyle=6.3.0
  - pydot=1.4.2
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pyjwt=2.6.0
  - pylint=2.16.2
  - pynacl=1.5.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyprojroot=0.2.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=7.2.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-eccodes=1.5.1
  - python-fastjsonschema=2.16.3
  - python-flatbuffers=23.1.21
  - python-libarchive-c=4.0
  - python_abi=3.10
  - pytoolconfig=1.2.5
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - qt-main=5.15.6
  - querystring_parser=1.2.4
  - r-abind=1.4_5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.2.2
  - r-base64enc=0.1_3
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-boot=1.3_28.1
  - r-broom=1.0.3
  - r-bslib=0.4.2
  - r-cachem=1.0.7
  - r-callr=3.7.3
  - r-car=3.1_1
  - r-cardata=3.0_5
  - r-caret=6.0_93
  - r-cellranger=1.1.0
  - r-class=7.3_21
  - r-cli=3.6.0
  - r-clipr=0.8.0
  - r-clock=0.6.1
  - r-codetools=0.2_19
  - r-colorspace=2.1_0
  - r-commonmark=1.8.1
  - r-conflicted=1.2.0
  - r-conquer=1.3.2
  - r-corrplot=0.92
  - r-cowplot=1.1.1
  - r-cpp11=0.4.3
  - r-crayon=1.5.2
  - r-curl=4.3.3
  - r-data.table=1.14.8
  - r-digest=0.6.31
  - r-dplyr=1.1.0
  - r-e1071=1.7_13
  - r-ellipsis=0.3.2
  - r-evaluate=0.20
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-fastmap=1.1.1
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_84
  - r-formattable=0.2.1
  - r-fs=1.6.1
  - r-future=1.31.0
  - r-future.apply=1.10.0
  - r-generics=0.1.3
  - r-ggplot2=3.4.1
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.3
  - r-ggsci=2.9
  - r-ggsignif=0.6.4
  - r-ggtext=0.1.2
  - r-globals=0.16.2
  - r-glue=1.6.2
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gridtext=0.1.5
  - r-gtable=0.3.1
  - r-hardhat=1.2.0
  - r-haven=2.5.1
  - r-here=1.0.1
  - r-highr=0.10
  - r-hms=1.1.2
  - r-htmltools=0.5.4
  - r-httr=1.4.5
  - r-ipred=0.9_13
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jpeg=0.1_10
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.4
  - r-kableextra=1.3.4
  - r-kernsmooth=2.23_20
  - r-knitr=1.42
  - r-labeling=0.4.2
  - r-lattice=0.20_45
  - r-lava=1.7.2
  - r-lifecycle=1.0.3
  - r-listenv=0.9.0
  - r-lme4=1.1_31
  - r-lubridate=1.9.2
  - r-magrittr=2.0.3
  - r-maptools=1.1_6
  - r-markdown=1.5
  - r-mass=7.3_58.2
  - r-matrix=1.5_3
  - r-matrixmodels=0.5_1
  - r-matrixstats=0.63.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_41
  - r-mime=0.12
  - r-minqa=1.2.5
  - r-mnormt=2.1.1
  - r-modelmetrics=1.2.2.2
  - r-multcomp=1.4_22
  - r-munsell=0.5.0
  - r-mvtnorm=1.1_3
  - r-nlme=3.1_162
  - r-nloptr=2.0.3
  - r-nnet=7.3_18
  - r-nparcomp=3.0
  - r-numderiv=2016.8_1.1
  - r-openssl=2.0.5
  - r-openxlsx=4.2.5.2
  - r-padr=0.6.2
  - r-parallelly=1.34.0
  - r-pbkrtest=0.5.2
  - r-pillar=1.8.1
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.8
  - r-png=0.1_8
  - r-polynom=1.4_1
  - r-prettyunits=1.1.1
  - r-proc=1.18.0
  - r-processx=3.8.0
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-progressr=0.13.0
  - r-proxy=0.4_27
  - r-ps=1.7.2
  - r-psych=2.2.9
  - r-purrr=1.0.1
  - r-quantreg=5.94
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.10
  - r-rcpparmadillo=0.11.4.4.0
  - r-rcppeigen=0.3.3.9.3
  - r-readr=2.1.4
  - r-readxl=1.4.2
  - r-recipes=1.0.5
  - r-rematch=1.0.1
  - r-reshape2=1.4.4
  - r-rio=0.5.29
  - r-rlang=1.0.6
  - r-rmarkdown=2.20
  - r-rpart=4.1.19
  - r-rprojroot=2.0.3
  - r-rstatix=0.7.2
  - r-rstudioapi=0.14
  - r-rvest=1.0.3
  - r-sandwich=3.0_2
  - r-sass=0.4.5
  - r-scales=1.2.1
  - r-selectr=0.4_2
  - r-sp=1.6_0
  - r-sparsem=1.81
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-stringi=1.7.12
  - r-stringr=1.5.0
  - r-survival=3.5_3
  - r-svglite=2.1.1
  - r-sys=3.4.1
  - r-systemfonts=1.0.4
  - r-th.data=1.1_1
  - r-tibble=3.1.8
  - r-tidyr=1.3.0
  - r-tidyselect=1.2.0
  - r-timechange=0.2.0
  - r-timedate=4022.108
  - r-tinytex=0.44
  - r-tmvnsim=1.0_2
  - r-tzdb=0.3.0
  - r-utf8=1.2.3
  - r-vctrs=0.5.2
  - r-viridislite=0.4.1
  - r-vroom=1.6.1
  - r-webshot=0.5.4
  - r-withr=2.5.0
  - r-xfun=0.37
  - r-xml2=1.3.3
  - r-yaml=2.3.7
  - r-zip=2.2.2
  - r-zoo=1.8_11
  - ray-air=2.3.0
  - ray-core=2.3.0
  - ray-dashboard=2.3.0
  - ray-data=2.3.0
  - ray-default=2.3.0
  - ray-serve=2.3.0
  - ray-train=2.3.0
  - ray-tune=2.3.0
  - re2=2022.06.01
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rich=13.3.1
  - ripgrep=13.0.0
  - rope=1.7.0
  - rsa=4.9
  - rstcheck=6.1.1
  - rstcheck-core=1.0.3
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - s2n=1.0.10
  - scikit-learn=1.2.1
  - scipy=1.10.1
  - sed=4.8
  - setproctitle=1.2.2
  - setuptools=65.6.3
  - shap=0.41.0
  - shapely=2.0.1
  - shellingham=1.5.1
  - sip=6.7.7
  - six=1.16.0
  - sleef=3.5.1
  - slicer=0.0.7
  - smart_open=6.3.0
  - smmap=3.0.5
  - snappy=1.1.9
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.2.post1
  - sphinx=6.1.3
  - sphinx-autobuild=2021.3.14
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlalchemy=1.4.46
  - sqlite=3.40.0
  - sqlparse=0.4.3
  - stack_data=0.6.2
  - starlette=0.25.0
  - sysroot_linux-64=2.12
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tensorboard=2.10.1
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorboardx=2.5
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.2.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.6
  - toolz=0.12.0
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - typer=0.4.2
  - types-docutils=0.18.3
  - types-pillow=9.4.0.17
  - types-setuptools=67.4.0.3
  - types-toml=0.10.8.5
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - ukkonen=1.0.1
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - uvicorn=0.20.0
  - virtualenv=20.19.0
  - watchgod=0.8.2
  - wcwidth=0.2.6
  - websocket-client=1.5.1
  - werkzeug=2.2.3
  - wheel=0.38.4
  - wrapt=1.15.0
  - xarray=2023.2.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.8.2
  - zarr=2.13.6
  - zipp=3.15.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - accelerate==0.16.0
      - copier==7.0.1
      - denoising-diffusion-pytorch==1.2.2
      - dunamai==1.16.0
      - einops==0.6.0
      - ema-pytorch==0.2.1
      - flake8-pyproject==1.2.2
      - iconarray==0.2.5
      - iteration-utilities==0.11.0
      - jinja2-ansible-filters==1.3.2
      - lion-pytorch==0.0.7
      - mistune==2.0.5
      - patsy==0.5.3
      - plumbum==1.8.1
      - psy-maps==1.4.2
      - psy-reg==1.4.0
      - psy-simple==1.4.1
      - pyyaml-include==1.3
      - questionary==1.10.0
      - sphinx-mdinclude==0.5.3
      - statsmodels==0.13.5
