name: aldernet
channels:
  - nvidia
  - conda-forge
dependencies:
  - anaconda-client
  - black
  - boa
  - cartopy
  - cfgrib
  - codespell
  - conda-build
  - cudatoolkit-dev=11.4.0
  - cudatoolkit=11.7.0
  - cudnn=8.4.1.50
  - flake8-black
  - flake8
  - graphviz
  - ipdb
  - isort
  - matplotlib
  - mccabe
  - mlflow
  - mypy
  - numpy
  - pandas
  - pillow
  - pip
  - pre-commit
  - psyplot
  - pydocstyle
  - pydot
  - pylint
  - pyprojroot
  - pytest
  - python
  - r-base
  - r-caret
  - r-conflicted
  - r-dplyr
  - r-formattable
  - r-ggplot2
  - r-ggpubr
  - r-ggtext
  - r-gridExtra
  - r-here
  - r-kableExtra
  - r-lubridate
  - r-magrittr
  - r-nparcomp
  - r-padr
  - r-psych
  - r-purrr
  - r-readr
  - r-rmarkdown
  - r-scales
  - r-stringr
  - r-tibble
  - r-tidyr
  - rich
  - rope
  - rstcheck
  - sphinx-autobuild
  - sphinx
  - tensorflow
  - toml
  - types-Pillow
  - types-PyYAML
  - types-setuptools
  - types-toml
  - xarray
  - zarr
  - pip:
    - copier
    - flake8-pyproject
    - iconarray
    - ipython
    - prometheus-client
    - protobuf>=4.25.3
    - ray[tune]
    - sphinx-mdinclude
